name: Generate Tests with Qodo Gen CLI

on:
  pull_request:
    branches:
      - '**'

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Qodo Gen CLI
        run: npm install -g qodo-gen-cli

      - name: Generate tests with Qodo Gen CLI
        run: qodo-gen
